config/routes.rb
Rails.application.routes.draw do
  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.is_admin?
  end

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque_web'
  end

  ActiveAdmin.routes(self)

  mount Facebook::Messenger::Server, at: 'bot'

  resources :line_items, only: [:create, :update]
  resources :orders, only: [:create, :index, :show, :destroy]
  resources :checkouts, only: :index
  resources :buildings, only: :index
  resources :landing_page, only: :index
  resources :notifications, only: [:index, :destroy]

  resource  :line_items, only: :destroy
  resource  :profiles, only: [:show, :edit, :update]
  resource  :passwords, only: [:edit, :update]

  get '/privacy', to: 'footer#privacy'
  get '/faqs', to: 'footer#faqs'
  get '/contact_us', to: 'footer#contact_us'
  get '/terms_of_use', to: 'footer#terms_of_use'
  get '/sms_terms_of_use', to: 'footer#sms_terms_of_use'
  get '/chowpartner_faqs', to: 'footer#chowpartner_faqs'
  get '/profiles/verify', to: 'profiles#verify'

  delete '/clear_notifications', to: 'notifications#destroy_all', as: :clear_notifications

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks', registrations: 'registrations' }
  root to: 'landing_page#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :check_if_user_has_phone_number

  def show
  end 

  def edit
  end

  def verify
    number = params[:number]
    api = SemaphoreApi.new
    api.send_number_verification_message(number, current_user)
  end

  def update
    @user = current_user

    if verify_number
      if @user.update(user_params)
        redirect_to profiles_url, notice: 'Profile has been updated.'
      else
        flash[:error] = @user.errors.full_messages.to_sentence
        render :edit
      end
    else
      flash[:error] = 'Invalid verification code.'
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :company_name, :floor, :building_id)
  end
  
  def verify_number
    # Removing number verification
    return true

    verification_code = params[:verification_code]
    @user.authenticate_otp(verification_code, drift: 60)
  end
end

app/views/profiles/edit.html.slim
.container style='width: 600px;'
  h3 Edit Profile
  hr
  fieldset
    = form_for current_user, url: profiles_path, method: :put, html: { class: 'form-horizontal edit-user' } do |f|
      = hidden_field_tag :verification_code
      .form-group
        = f.label :name, class: 'control-label col-md-2 col-sm-2 col-xs-12'
        .col-md-10.col-xs-12.col-sm-10
          = f.text_field :name, class: 'form-control', autofocus: true
      .form-group
        = f.label :email, class: 'control-label col-md-2 col-sm-2 col-xs-12'
        .col-md-10.col-xs-12.col-sm-10
          = f.email_field :email, class: 'form-control', required: true
      .form-group
        = f.label :phone_number, class: 'control-label col-md-2 col-sm-2 col-xs-12'
        .col-md-10.col-xs-12.col-sm-10
          = f.text_field :phone_number, class: 'form-control', required: true, pattern: '^09\d{9}$'
          span.help-block ex. 09051234567
      .form-group
        = f.label :building_id, class: 'control-label col-md-2 col-sm-2 col-xs-12'
        .col-md-10.col-xs-12.col-sm-10
          = f.select :building_id, Building.all.collect{|x| [x.name, x.id]}, {include_blank: 'Select building'}, class: 'form-control'
          = link_to "Add your building", 'https://trychowpocket.typeform.com/to/FBRzNy', class: 'login-page__activate-building', target: '_blank'
      .form-group
        = f.label :company_name, class: 'control-label col-md-2 col-sm-2 col-xs-12'
        .col-md-10.col-xs-12.col-sm-10
          = f.text_field :company_name, class: 'form-control', required: true
      .form-group
        = f.label :floor, class: 'control-label col-md-2 col-sm-2 col-xs-12'
        .col-md-10.col-xs-12.col-sm-10
          = f.text_field :floor, class: 'form-control', required: true
      .form-group
        .btn-group.col-md-10.col-md-offset-2
          = f.submit 'Save', class: 'btn btn-success'
          button.btn.btn-warning type='reset'
            | Reset
          = link_to 'Cancel', profiles_path, class: 'btn btn-danger'
    

app/views/profiles/show.html.slim
h3 My Profile
hr
.row
  .col-md-3.col-xs-12
    | Name:
  .col-md-9.col-xs-12
    b
      = current_user.name
  .col-md-3.col-xs-12
    | Email:
  .col-md-9.col-xs-12
    b
      = current_user.email
  .col-md-3.col-xs-12
    | Phone Number:
  .col-md-9.col-xs-12
    b
      = current_user.phone_number || '--'
  .col-md-3.col-xs-12
    | Building:
  .col-md-9.col-xs-12
    b
      = current_user.building.try(:name) || '--'
  .col-md-3.col-xs-12
    | Company Name:
  .col-md-9.col-xs-12
    b
      = current_user.company_name || '--'
  .col-md-3.col-xs-12
    | Floor Number:
  .col-md-9.col-xs-12
    b
      = current_user.floor || '--'
hr
.btn-group style='margin-bottom: 20px;'
  = link_to icon('pencil', ' Edit Profile'), edit_profiles_path, class: 'btn btn-info btn-sm'
  - if current_user.provider.nil?
    = link_to icon('key', ' Change Password'), edit_passwords_path, class: 'btn btn-warning btn-sm'