config/routes.rb
Rails.application.routes.draw do
  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.is_admin?
  end

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque_web'
  end

  ActiveAdmin.routes(self)

  mount Facebook::Messenger::Server, at: 'bot'

  resources :line_items, only: [:create, :update]
  resources :orders, only: [:create, :index, :show, :destroy]
  resources :checkouts, only: :index
  resources :buildings, only: :index
  resources :landing_page, only: :index
  resources :notifications, only: [:index, :destroy]

  resource  :line_items, only: :destroy
  resource  :profiles, only: [:show, :edit, :update]
  resource  :passwords, only: [:edit, :update]

  get '/privacy', to: 'footer#privacy'
  get '/faqs', to: 'footer#faqs'
  get '/contact_us', to: 'footer#contact_us'
  get '/terms_of_use', to: 'footer#terms_of_use'
  get '/sms_terms_of_use', to: 'footer#sms_terms_of_use'
  get '/chowpartner_faqs', to: 'footer#chowpartner_faqs'
  get '/profiles/verify', to: 'profiles#verify'

  delete '/clear_notifications', to: 'notifications#destroy_all', as: :clear_notifications

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks', registrations: 'registrations' }
  root to: 'landing_page#index'
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: :destroy

  def index
    @notifications = current_user.notifications.order(created_at: :desc)
    set_read_notifications
  end

  def destroy
    @notification.destroy
    redirect_to notifications_path, notice: 'Notification Deleted'
  end

  def destroy_all
    @notifications = current_user.notifications
    @notifications.destroy_all
    redirect_to notifications_path, notice: 'Notifications Cleared'
  end

  private
  def set_notification
    @notification = current_user.notifications.find(params[:id])
  end

  def set_read_notifications
    @notifications.update_all(status: NotificationStatuses::READ)
  end
end

app/views/notifications/index.html.slim
.clearfix
  .pull-left
    h3 Notifications
  .pull-right
    = link_to icon('times-circle', ' Clear'), clear_notifications_path, class: 'btn btn-link', style: 'color: red; padding: 25px 0;', method: :delete
hr
- if @notifications.present?
  - @notifications.each do |notif|
   .panel.panel-default
      .panel-body
        p.text-muted
          = time_ago_in_words(notif.created_at) + ' ago'
        p
         = notif.message
        br
        .btn-group
         - if notif.notification_type == NotificationTypes::ORDER
          = link_to icon('list-ul', ' View Order History'), orders_path, class: 'btn btn-primary'
          = link_to icon('trash', ' Delete'), notification_path(notif), class: 'btn btn-danger', method: :delete
- else
  div style='padding: 200px 0;'
    h2.text-center You have no notifications.