config/routes.rb
Rails.application.routes.draw do
  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.is_admin?
  end

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque_web'
  end

  ActiveAdmin.routes(self)

  mount Facebook::Messenger::Server, at: 'bot'

  resources :line_items, only: [:create, :update]
  resources :orders, only: [:create, :index, :show, :destroy]
  resources :checkouts, only: :index
  resources :buildings, only: :index
  resources :landing_page, only: :index
  resources :notifications, only: [:index, :destroy]

  resource  :line_items, only: :destroy
  resource  :profiles, only: [:show, :edit, :update]
  resource  :passwords, only: [:edit, :update]

  get '/privacy', to: 'footer#privacy'
  get '/faqs', to: 'footer#faqs'
  get '/contact_us', to: 'footer#contact_us'
  get '/terms_of_use', to: 'footer#terms_of_use'
  get '/sms_terms_of_use', to: 'footer#sms_terms_of_use'
  get '/chowpartner_faqs', to: 'footer#chowpartner_faqs'
  get '/profiles/verify', to: 'profiles#verify'

  delete '/clear_notifications', to: 'notifications#destroy_all', as: :clear_notifications

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks', registrations: 'registrations' }
  root to: 'landing_page#index'
end

app/views/shared/_alerts.html.slim
div style='margin: 10px 0;'
  - flash.each do |key, content|
    - unless key == 'timedout'
      .alert.alert-dismissable class="alert-#{key == 'notice' ? 'success' : 'danger'}"
        btn.close data-dismiss='alert' type='button' &times;
        .flash class="flash--#{key}" #{content.html_safe} 

app/views/shared/_footer.html.slim
.footer style='background-color: #444; color: white;'
  .container
    .row
      .col-md-4.col-xs-12
        h4 Getting Started
        p
          a href='/faqs' FAQs
        p
          a href='/chowpartner_faqs' Chowpartner FAQs
        p
          a href='https://trychowpocket.typeform.com/to/FBRzNy' target='_blank'  Activate delivery in your building
      .col-md-4.col-xs-12
        h4 Resources
        p
          a href='/privacy' Privacy Policy
        p
          a href='/terms_of_use' Terms of Use
        p
          a href='/sms_terms_of_use' SMS Terms of Use
      .col-md-4.col-xs-12
        h4 Connect
        p
          a href='/contact_us' Contact Us
        p.footer__social-links
          = link_to icon('facebook-official'), 'https://www.facebook.com/trychowpocket/', target: '_blank'
          = link_to icon('twitter'), 'https://twitter.com/chowpocket', target: '_blank'
          = link_to icon('instagram'), 'https://www.instagram.com/trychowpocket/', target: '_blank'
        p
          a class="github-button" href="https://github.com/jnsoo123" data-show-count="true" aria-label="Follow @jnsoo123 on GitHub"
            | Follow @jnsoo123
        p
          a class="github-button" href="https://github.com/jnsoo123/chowpocket" data-show-count='true'  data-icon="octicon-star" aria-label="Star jnsoo123/chowpocket on GitHub"
            | Star

.footer2 style='background-color: #333; color: white;'
  .container
    div
      | All Rights Reserved. Forage Co. &copy; 2017.

app/views/shared/_modals.html.erb
<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title center" id="myModalLabel">Login to Chowpocket</h4>
      </div>
      <div class="modal-body">
        <%= form_for(User.new, url: new_user_session_path) do |f| %>
          <div class='form-group'>
            <%= link_to omniauth_authorize_path(User.new, :google_oauth2), class: 'btn btn-google2' do %>
              <div class="google-icon"></div>
              <div class="google-text">Log In with Google</div>
            <% end %>
          </div>
          <div class='form-group'>
            <%= link_to user_facebook_omniauth_authorize_path, class: 'btn btn-default btn-facebook' do %>
              <div class="facebook-icon"></div>
              <div class="facebook-text">Log In with Facebook</div>
            <% end %>
          </div>
        <% end %>
        <hr />
        <p class="text-center">OR <br>Use your email</p>
        <hr />
        <%= link_to 'Log In / Sign up', new_user_session_path, class: 'btn btn-warning', style: 'width: 100%;' %>
        <br />
        <br />
        <p class='text-center'>
        <small class='text-muted'>By logging in, you agree to Chowpocket's <%= link_to 'Terms of Use', terms_of_use_path %> and <%= link_to 'Privacy Policy', privacy_path %>.</small>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="verify-modal" tabindex="-1" role="dialog" aria-labelledby="verifyModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Verify Phone Number</h4>
      </div>
      <div class="modal-body">
        <div class='form-group'>
          <label class='control-label'>Enter Verification Code Sent From Your Mobile Device</label>
          <input type='text' class='form-control' id='verification-code-modal' placeholder='Enter 6 Digit Verification. Eg: (123456)' minlength='6' maxlength='6'  required />
        </div>
      </div>
      <div class='modal-footer'>
        <button type='button' class='btn btn-warning' id='submit-verification'>Submit</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.slim
nav.nav.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-target="#navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Chowpocket', root_path, class: 'navbar-brand'
    #navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right.navbar__links
        li
          = link_to icon('cutlery', ' Schedule a FoodPartner Demo', style: 'margin-right: 8px;'), 'https://trychowpocket.typeform.com/to/PWjYyk', target: '_blank'
        - if not user_signed_in?
          li
            = link_to icon('user', ' Log In', style: 'margin-right: 8px;'), '#', data: { toggle: 'modal', target: '#signup-modal' }
        - else
          li
            = link_to notifications_path do
              = icon('bell', ' Notifications')
              span.badge
                = current_user.unread_notifications_count

          li.dropdown
            a.dropdown-toggle href='#' data-toggle='dropdown' role='button' aria-expanded='false'
              = icon('user', " #{current_user.name} ", style: 'margin-right: 8px;')
              span.caret
            ul.dropdown-menu role='menu'
              - if current_user.is_admin?
               li
                  = link_to icon('cogs', ' Administrator'), admin_root_path
              li
                = link_to icon('user', ' My Profile'), profiles_path
              li
                = link_to icon('list-ul', ' Order History'), orders_path
              li.divider
              li
                = link_to icon('sign-out', ' Logout'), destroy_user_session_path, method: :delete

= render partial: 'shared/modals'